name: git-issue-release

on:
  push: # Automatically create or update issues when pull request is merged.
    branches:
      - git-issue-release
  release: # Automatically close the latest issue when release is published.
    types: [released]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: git-issue-release
        uses: kouki-dan/git-issue-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.HELEEEN_TOKEN }}
        with:
          release-tag-pattern: ^v # Use it to find the latest release. `^v` means starts with v.
          release-label: "release" # Use it to find release issues. Labels are not created automatically, so create them before use it.
          description: "Revision: ${{ github.sha }}"
