---
name: env test
on:
  push:

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "TEST=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: echo ${{ env.TEST }}
